#ifndef __RMI_P2_CONFIG
#define __RMI_P2_CONFIG

#define RIGHT 			true
#define LEFT 			false

#define ROBOT_WIDTH 	20.0

#define TURN_RADIUS_SMALL	18.0
#define TURN_RADIUS_MEDIUM 	25.0
#define TURN_RADIUS_BIG		30.0	

#define SPEED_SLOW 			30
#define SPEED_MEDIUM 		50
#define SPEED_FAST 			80
#define SPEED_ROTATE 		60
#define SPEED_ROTATE_SLOW	30
#define SPEED_FOLLOW_WALL 	50

#define DISTANCE_FOLLOW_WALL_IDEAL_MIN	400
#define DISTANCE_FOLLOW_WALL_IDEAL_MAX	320 
#define DISTANCE_FOLLOW_WALL_SIDES 		300 	
#define DISTANCE_FOLLOW_WALL_FRONT 		650 	
#define DISTANCE_COLISION_FRONT			700		
#define DISTANCE_COLISION_SIDES			600		
#define DISTANCE_NEAR_FRONT				200
#define DISTANCE_NEAR_SIDES				450	
#define DISTANCE_FAR_SIDES				200	


#endif


